name: Sync to LetsGetRidOfThatBuzz

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Trigger sync in LetsGetRidOfThatBuzz
      run: |
        curl -X POST \
          -H "Authorization: token ${{secrets.BUZZ}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/mtet88/letsgetridofthatbuzz/actions/workflows/sync.yml/dispatches \
          -d '{"ref":"main"}'
